.PHONY: gen

gen:
	xcodegen generate
	@printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>com.apple.security.app-sandbox</key>\n\t<true/>\n\t<key>com.apple.security.network.client</key>\n\t<true/>\n\t<key>com.apple.security.files.user-selected.read-write</key>\n\t<true/>\n\t<key>com.apple.security.application-groups</key>\n\t<array>\n\t\t<string>group.net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n\t<key>keychain-access-groups</key>\n\t<array>\n\t\t<string>$$(AppIdentifierPrefix)net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n</dict>\n</plist>\n' \
		> VikunjaWidgetApp/VikunjaWidgetApp.entitlements
	@printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>com.apple.security.app-sandbox</key>\n\t<true/>\n\t<key>com.apple.security.network.client</key>\n\t<true/>\n\t<key>com.apple.security.application-groups</key>\n\t<array>\n\t\t<string>group.net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n\t<key>keychain-access-groups</key>\n\t<array>\n\t\t<string>$$(AppIdentifierPrefix)net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n</dict>\n</plist>\n' \
		> VikunjaWidgetExtension/VikunjaWidgetExtension.entitlements
	@printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>com.apple.security.application-groups</key>\n\t<array>\n\t\t<string>group.net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n\t<key>keychain-access-groups</key>\n\t<array>\n\t\t<string>$$(AppIdentifierPrefix)net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n</dict>\n</plist>\n' \
		> VikunjaWidgetApp/VikunjaWidgetAppIOS.entitlements
	@printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>com.apple.security.application-groups</key>\n\t<array>\n\t\t<string>group.net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n\t<key>keychain-access-groups</key>\n\t<array>\n\t\t<string>$$(AppIdentifierPrefix)net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n</dict>\n</plist>\n' \
		> VikunjaWidgetExtension/VikunjaWidgetExtensionIOS.entitlements
	@printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>com.apple.security.application-groups</key>\n\t<array>\n\t\t<string>group.net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n\t<key>keychain-access-groups</key>\n\t<array>\n\t\t<string>$$(AppIdentifierPrefix)net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n</dict>\n</plist>\n' \
		> VikunjaWidgetWatch/VikunjaWidgetWatch.entitlements
	@printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>com.apple.security.application-groups</key>\n\t<array>\n\t\t<string>group.net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n\t<key>keychain-access-groups</key>\n\t<array>\n\t\t<string>$$(AppIdentifierPrefix)net.angstreich.VikunjaWidgetApp</string>\n\t</array>\n</dict>\n</plist>\n' \
		> VikunjaWidgetWatchExtension/VikunjaWidgetWatchExtension.entitlements
	@echo "✓ Entitlements restored (six files)"
